services:
  - type: web
    name: chatlegaldesign
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://noqzwkkdfpbmglewsozo.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
